Remove set -e from scripts

diff --git a/gcp-secrets/ci-script b/gcp-secrets/ci-script
--- a/gcp-secrets/ci-script
+++ b/gcp-secrets/ci-script
@@ -6,8 +6,6 @@
 # Usage
 # . /tmp/ci-script <CI job name>
 
-set -e
-
 # CI_JOB is used to setup and patch code based on job type
 if [ -z ${1} ]
 then
@@ -24,6 +22,12 @@ echo "${BASTION_IP} cluster.ppc64le registry.ppc64le ppc64le" >> /etc/hosts
 
 #copy env setup script
 scp -i /opt/cluster/knative-ssh -o MACs=hmac-sha2-256 -o StrictHostKeyChecking=no -oLogLevel=ERROR -o UserKnownHostsFile=/dev/null root@cluster.ppc64le:/opt/knative-upstream-ci/setup-environment.sh /tmp
+
+if [ ! -f /tmp/setup-environment.sh ]
+then
+    echo "Couldn't fetch file from remote machine...."
+    exit 1
+fi
 
 #run env setup script
 chmod +x /tmp/setup-environment.sh
